### ISSUE TITLE
vibe.d code with subproject is not loaded properly into dcd

### ISSUE THREAD

**Issue by yannick** [Pure-D/code-d#12]
i can't resolve vibe.d code. 

i do not understand the whole typescript dcd business but i have not found any reference to 
dub describe.

ideally you should get all valid source files to be added to dcd from a ```dub describe``` run !

**Comment by WebFreak001** [comment]
Pull and build most recent workspace-d, do Ctrl-Shift-P -> code-d: Switch Configuration

Then select the configuration you use in dub

If you still experience issues try restarting vscode, open the console (`Developer: Toggle Developer Tools`) and at the top it should be saying `> Array[n]` where n is any number. Try expanding that and verify that all import paths are correct in there. I am using the dub package instead of dub describe because then it wont reload all the import paths, configurations, etc. every time I use dub describe. This will become very useful in later releases when dub build will be implemented for linting.

If all import paths are correct its most likely DCDs fault, there are many issues about vibe.d there

**Comment by yannick** [comment]
we'll i think it would be better to use dub describe, it can be easily cached and the paths could be cached aswell if it really starts to be slow. but you also don't know if any of the dependency files in the dub repo changed so i think its correct to reload all the files.

also, how can you be sure which source files belong to the package by not reading dub describe? 
you will never know as you any library can specify any random files to be included for compilation from its dub.json. 

so imho the correct way of doing it is using dub describe and letting the user choose himself when to reload dcd compeltely. only he knows anyways.

that said i checked for the values in vscode:
it contains ```path/to/dub-dependencies/vibe.d/source/vibe```
and a vibe source file that is not picked up is e.g. in
```dub-dependencies/vibe.d/source/vibe/http/server.d```
so its actually a code-d bug (-> https://github.com/Hackerpilot/DCD#configuration-files )

**Comment by WebFreak001** [comment]
It is using the official dub package. Dub describe calls the exact same functions like my code does. The problem here is that its a single source file and DCD does not support adding single source files as search files, only folders.

**Comment by yannick** [comment]
not sure what you mean by "official dub package".
its not about a single source file, the thing is that you include 
```vibe.d/source/vibe```  where as the source files reside in subfolders there in!
so all those need to be added to dcd too!

**Comment by WebFreak001** [comment]
https://github.com/D-Programming-Language/dub/ this is the dub executable. It also has an api and a package on dub so people can include dub without the executable being needed.

I am just adding the source files dub gives me.

For me it says `~/.dub/packages/vibe-d-0.7.26/source/` instead of `source/vibe` at the end.

Try importing `vibe.vibe` or the separate modules instead of `vibe.d` as it supports the symbols for me.

When typing `import vibe.vibe :` it should show all vibe symbols. But somehow it doesnt work on global level then. Im pretty sure this is a DCD issue as DCD clearly detects all files but not uses them correctly with all these public imports in there.

It works with hovering over the symbols (showing documentation). Im pretty sure this is this bug: https://github.com/Hackerpilot/DCD/issues/273

**Comment by yannick** [comment]
steps to reproduce:

create a new vibe app:
```dub -t vibe.d testvibe```

replace ```dub.sdl`` with:

```
name "testvibe"
dependency "vibe-d" version="~master"
versions "VibeDefaultMain"
```

then try to follow any reference.

**Comment by yannick** [comment]
i dont think its Hackerpilot/DCD#273

in
https://github.com/Hackerpilot/DCD#configuration-files 
it says:

```
Keep in mind that DCD treats import paths the same way that the compiler does. For example, a configuration file like this will not work as expected:

/usr/include/dmd/
What you actually want is this:

/usr/include/dmd/druntime/import
/usr/include/dmd/phobos
```
which to me says that dcd only looks in the exact folder and not in subfolders.
but i really think it should be a list of all files the dub api gives you and not folders, as dub allows to add single files to be included.

**Comment by WebFreak001** [comment]
dub allows single files to be included but DCD does not. It only supports folders. Also using `import vibe.vibe` instead of `import vibe.d` works. For the compiler both are the same but DCD does not follow it in the first import. In the second looking up documentation works but auto completion is broken. This is exactly what they discussed on that issue.

Are you sure it says `path/to/dub-dependencies/vibe.d/source/vibe` instead of `path/to/dub-dependencies/vibe.d/source`? Because for both master and versioned works for me as intended (the latter)

**Comment by yannick** [comment]
ok got it, i was not aware that dcd does not allow single files.
 ```import vibe.vibe``` works indeed.
cool. and thanks for the great plugin, i really start to like vscode.
