### ISSUE TITLE
Broken highlighting on numeric literals with underscores

### ISSUE THREAD

**Issue by storm20200** [Pure-D/code-d#124]
Hi there. I found an issue which causes the syntax highlighting to break when displaying numeric literals. The issue comes from the fact that numeric literals can actually contain underscores to help with readability. An example is shown below:

![syntaxhighlightissue](https://cloud.githubusercontent.com/assets/6877847/24874028/10f7d88e-1e1b-11e7-8267-cf19446b8460.png)

You can see that numeric literals without underscores highlight fine but using an underscore breaks it. Note: underscores can be used at any point in the numbers, after the first digit.

**Comment by WebFreak001** [comment]
right now only in the code-d-beta package which will be merged into master eventually, but it's fixed once it's in there. Switched to https://github.com/ysgard/d-struct grammar now because it looks a lot better maintained and the authors suggested me to use it in the atom extension which I will also do
