### ISSUE TITLE
Code-d 0.16.2

### ISSUE THREAD

**Issue by Wulfklaue** [Pure-D/code-d#131]
I keep getting a update icon for version 0.16.2 in VSC ( 1.13.1 ), so tried to update ... nothing happens. Normally it needs to ask to restart. Close VSC and ... 0.16.2 is marked as installed.

On my work PC, update to 0.16.2 comes up. Press update and ... code-d even vanished from the plugin list and trying to reinstall same effect. Very strange behavior and it only happens with code-d.

PS: Please also take a look at this thread regarding Code-d:
https://forum.dlang.org/thread/mailman.4150.1499143780.31550.digitalmars-d@puremagic.com?page=1

**Comment by WebFreak001** [comment]
It might happen on windows because the executables are still opened and it can't delete the old directory. It used to work in other versions of vscode because it simply kept the old plugin directory but I guess they changed how that worked. Might be better to install that to a known location or see how the C# extension does it. I am also reading through that forum post, though I think code-d was a lot earlier considering it was one of the first plugins for vscode (my debugging extension came shortly after, still when there were only like 5 debuggers) but I need to finish reading that entire thread later today

**Comment by WebFreak001** [comment]
can't reproduce anymore and very outdated
