### ISSUE TITLE
Lambda operator (=>) not recognized

### ISSUE THREAD

**Issue by weltensturm** [Pure-D/code-d#138]
There's no entry in the syntax file for lambdas, eg. `(a, b) => a+b`, which causes `=` and `>` to be styled differently from another. This in turn makes fonts with ligature support kinda useless.

Fira Code in code-d vs plain text:
![image](https://user-images.githubusercontent.com/811167/29240826-261354c4-7f6d-11e7-9d39-6f5be60653e5.png)

A quick fix:
```xml
		<dict>
			<key>match</key>
			<string>(=&gt;)</string>
			<key>name</key>
			<string>keyword.operator.lambda.d</string>
		</dict>
```

But this doesn't capture parameters and stuff correctly.

**Comment by WebFreak001** [comment]
so it happens because these are two separate tokens? Should be easy to fix, do you have a font I can test it with?

**Comment by weltensturm** [comment]
Yes and yes: https://github.com/tonsky/FiraCode

**Comment by WebFreak001** [comment]
right now only in the code-d-beta package which will be merged into master eventually, but it's fixed once it's in there. Switched to https://github.com/ysgard/d-struct grammar now because it looks a lot better maintained and the authors suggested me to use it in the atom extension which I will also do
