### ISSUE TITLE
string not recognized via syntax highlight

### ISSUE THREAD

**Issue by jblachly** [Pure-D/code-d#238]
string is a special case of array; arrays of all base types are recognized and highlighted as the base type:

https://github.com/Pure-D/code-d/blob/ee701bc0621830c9955de9aac12f91e40e1ef30d/syntaxes/d.json#L39

However, string is not listed there.

This may be controversial and already covered(?), but given the special status imbued upon `string` by the language designer (http://www.drdobbs.com/architecture-and-design/cs-biggest-mistake/228701625 among others), I expected string to be highlighted the same as the other base types.

**Comment by WebFreak001** [comment]
I removed string from being highlit because it is not actually part of the language, but defined in the druntime. So you can name your stuff `string` because it's not a keyword, which can be useful for enums. I removed string from this list because it is not a keyword but a normal type like any other custom defined type. It can also be removed if you don't use the D runtime.

It is a bit confusing when having code which uses `string` as identifier when string is highlit as keyword, so that's why I removed it in the first place, but it's a pretty rare case and pretty much only found in tagged union/serialization code.

Maybe it could be added again though because it is so commonly used and very rare not to be used as type.

**Comment by jblachly** [comment]
Whatever you decide, thank you for your thoughtful and reasoned reply.
