### ISSUE TITLE
How to stop running ?

### ISSUE THREAD

**Issue by vinodvinu** [Pure-D/code-d#270]
Hi,
 I am newbie in D
I would like to know how to stop the running code. Is there any short cuts ? Thanks in advance.

**Comment by WebFreak001** [comment]
if you use the debugger to run your code, you can just click the stop button to close your program or otherwise the normal ways to close your program (hit the X button on a GUI window, press Ctrl-C in command line or kill the process using the task manager or command line)

If you use the integrated terminal in vscode or the build tasks (ctrl-shift-b) it's the latter ways of closing it, otherwise if you run your app using the debugger it's the first way of closing it.
