### ISSUE TITLE
Type documentation includes comments that aren't related

### ISSUE THREAD

**Issue by dgellow** [Pure-D/code-d#307]
Hi there,

First let me thank you for this plugin, I just started learning about D and it is working almost perfectly with zero config!

While copy pasting some examples I found out a small issue in the documentation available when hovering a type or a function: in addition to the object doc comment, the documentation also includes any comment block present before it.

## Example with `Throwable`

I'm hovering `Throwable` , the documentation contains a bunch of `////////`, taking two lines of vertical space.

![image](https://user-images.githubusercontent.com/2451004/80522674-3e7d1400-898d-11ea-8520-0082594b548e.png)

Looking at `Throwable` definition we can see that there is a bunch of decorative comments.

![image](https://user-images.githubusercontent.com/2451004/80522721-4fc62080-898d-11ea-8cc7-f119d807875a.png)

**Comment by WebFreak001** [comment]
opened an issue on libdparse about this, it seems because the comment block uses `//` for the Throwable it shouldn't be parsed as ddoc block.

Otherwise the ddoc spec doesn't say how to handle the extra whitespace and only says that all ddoc comment blocks always apply to the next declaration, so if there was a `/// Throwable` it would in theory be correct.

**Comment by WebFreak001** [comment]
fixed in latest serve-d
