### ISSUE TITLE
Updating the Textmate Syntax

### ISSUE THREAD

**Issue by doug-clayton** [Pure-D/code-d#309]
Hi,

This is more of a request, than anything. I've been working on a theme geared towards D specifically (https://github.com/DougClayton4231/theme-fantastique) and I built it around the Textmate syntax file in Laurent Tréguier's (https://github.com/d-language-server/vscode-dlang) project, as those were the most fleshed out that I could find. They're really great at providing support for a lot of granular patterns, but his project has been archived. Would it be possible to take on his syntax or update the current syntax to provide more control? If not, I can keep copy pasting his syntax file locally :)

Thanks!

**Comment by WebFreak001** [comment]
uhh can you instead give examples which parts need changing for you? The syntax in code-d works quite well at this point, I'm rarely finding issues with it anymore. If you can find in general things which use wrong textmate types, I can easily change them then too.

I would rather not again completely redo all the users syntaxes

**Comment by DougClayton4231** [comment]
Sounds good :) Here's a list of things I couldn't find out how to get working:

- All caps constants (e.g., ENUM_EXAMPLE)
- Struct\Class\Interface\Enum names outside of their declaration scope.
- Alias names in and out of their declaration scope.
- A bunch of the tokens aren't available outside of keyword.token (e.g., null, true, false, etc.). This is actually very nice in Laurent's version, where he has bindings for multiple different subsets of these tokens (e.g., constant.language.boolean, constant.language.null, etc.).
- Variable parameters.
- The size_t keyword.
- There's a # in the definition for "#keyword.control.in.d". Is this intentional or should I ignore it?

Sorry for the giant list! I really appreciate any help that you can give me.

**Comment by WebFreak001** [comment]
* All caps constants (e.g., ENUM_EXAMPLE)
    * not a fan of hardwiring this into the highlighter. (especially because this is not D-style) However since the last 2 vscode releases it is now possible to highlight parts by code. So basically I can mark enums as enums and types as types - see #299 
* Struct\Class\Interface\Enum names outside of their declaration scope
    * well same issue really, can't highlight with 100% accuracy
* Alias names in and out of their declaration scope
    * ditto
* A bunch of the tokens aren't available outside of keyword.token (e.g., null, true, false, etc.). This is actually very nice in Laurent's version, where he has bindings for multiple different subsets of these tokens (e.g., constant.language.boolean, constant.language.null, etc.).
    * I can add that to those
* Variable parameters.
    * example?
* The size_t keyword
    * size_t isn't a keyword, but because I also included string now I guess I could include size_t and ptrdiff_t as well
* There's a # in the definition for "#keyword.control.in.d". Is this intentional or should I ignore it?
    * oh gonna fix that now

You need your theme to specifically opt-in to semanticHighlighting, check the docs on that. (Though there is no implementation for it yet and I think it might be a while until that is in)

**Comment by WebFreak001** [comment]
note: for the tokens I have just made every token a different scope like `keyword.token.true.d`

So you can just style each one how you want it.

**Comment by DougClayton4231** [comment]
Awesome :) Thanks so much for your help! I added the semanticHighlighting flag and colors for whenever support is added.

The variable.parameter name doesn't seem to grab parameters of structs, classes, etc.. In Laurent's version, "support.constant.property.d"and "variable.other.member.d" seem to cover all of the variable members and builtin property key names. Is there a specific name I need to use?

**Comment by WebFreak001** [comment]
I think I might want to delay the semantic highlighting implementation a little bit, otherwise it will turn out like the Java extension:

![buggy semantic highlighting](https://wfr.moe/f6x8L0.png)
![buggy semantic highlighting](https://wfr.moe/f6x8qw.png)

because right now serve-d is not stable or fast enough for something which could turn out like this

**Comment by WebFreak001** [comment]
merging with #299 then
