### ISSUE TITLE
Could not update import paths / Could not upgrade dub project if toolchainRequirements it's present on dub.json

### ISSUE THREAD

**Issue by Zardoz89** [Pure-D/code-d#355]
To reproduce, simply create the "Hello world" project with Code-d, and add this to dub.json & save : 
```json
{
	"toolchainRequirements": {
		"dub": ">=1.19.0"
	}
}
```
Visual Code, would show a "Could not update import paths. Please check your build settings in the status bar."
If the dub.json it's saved again, then a "Could not upgrade dub project" error will be show : 

![imagen](https://user-images.githubusercontent.com/888483/117065902-54ec4700-ad28-11eb-8027-78976ac72599.png)

---

Ubuntu 20.04.2 LTS
DUB version 1.23.0, built on Sep 27 2020
DMD64 D Compiler v2.096.1

Visual Code
Version: 1.55.2
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:37:02.931Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.4.0-54-generic

Code-D v0.22.0

`code-d & serve-d` output : 
```
2021-05-04T22:39:07.533 [trace] app.d:79:processRequest Calling provideCodeActions
2021-05-04T22:39:07.543 [trace] app.d:79:processRequest Calling provideDocumentSymbols
/home/luis/repos/dlang/prueba_coded/dub.json(1:1)[error]: declaration expected instead of `{`
/home/luis/repos/dlang/prueba_coded/dub.json(3:27)[error]: Declaration expected
/home/luis/repos/dlang/prueba_coded/dub.json(7:1)[error]: Declaration expected
2021-05-04T22:39:07.755 [trace] app.d:79:processRequest Calling provideCodeActions
2021-05-04T22:39:07.765 [trace] app.d:79:processRequest Calling provideCodeLens
2021-05-04T22:39:08.409 [trace] app.d:79:processRequest Calling provideCodeActions
2021-05-04T22:39:08.822 [info] dub.d:156:onDidSaveDubRecipe Updating dependencies
[progress] [00876.519] [importUpgrades] 0 / 10: file:///home/luis/repos/dlang/prueba_coded
[progress] [00876.519] [importUpgrades] 10 / 10: file:///home/luis/repos/dlang/prueba_code
```

**Comment by WebFreak001** [comment]
Are you on serve-d nightly? The stable (default) one might still have an outdated dub which didn't support that feature

**Comment by Zardoz89** [comment]
I just saw that the default version of serve-d it's the source of the problem.

**Comment by Zardoz89** [comment]
I'm closing this issue, but I suggest recommend closing a new version of serve-d and use it as default or suggest on documentation using the beta channel because this incompatibilities with modern dub.

**Comment by SandaruKasa** [comment]
Just run into the same issue, but under slightly different circumstances: I have dub installed from Arch repositories, so it's pretty fresh (`DUB version 1.31.1, built on Feb 20 2023`).

Code-d was using this dub and gave me the same error: "Could not update import paths. Please check your build settings in the status bar."

I've managed to solve it by installing "serve-d-git" from AUR and making code-d use it instead of a `stable` bundled version.

I guess it would be nice to have a more concise error message for this version mismatch case, and/or ship `beta` version of serve-d (as it was suggested above).

Thanks for the plugin though! Not sure if I would even look into D if there was no IDE support.
