### ISSUE TITLE
Bug: hover ddoc picking up all overloaded functions

### ISSUE THREAD

**Issue by al1-ce** [Pure-D/code-d#439]
If you have multiple overloaded functions with ddoc, aka
```d
/**
Does thing 1
*/
void dothing(int i) {} 

/**
Does thing 2
*/
void dothing(string s) {} 
```
It's going to pick up and display all of them at first

Also templated overloaded functions arent showing correct ddoc, only one that is declared first

**Comment by WebFreak001** [comment]
hover showing all overloaded function is because
1) regular ddoc gets combined like this too, usually the functions are related and you are probably interested in all of them
2) DCD does not always resolve to the correct function, so this also doubles as fail-safe to actually show something that's correct

**Comment by al1-ce** [comment]
Honestly its a hot mess
One thing is when online document statically showong you all the data and other thing is when you code
Dcd might not pick up correct function but user still can switch viewed function in popup
