### ISSUE TITLE
Go to Definition

### ISSUE THREAD

**Issue by Damanox** [Pure-D/code-d#45]
Go to Definition sometimes does not work or move cursor to line or even file, that does not contains this variable.
OS: Windows 10 x64
Code-D: 0.10.10
Workspace-D: 2.7.1+commit.11.gc27329c
![691f52bb05](https://cloud.githubusercontent.com/assets/545324/15721468/cc6c375c-2841-11e6-81d8-baef121ec09f.png)

**Comment by WebFreak001** [comment]
It's because it's a template function and it can't know which function it should show you without you providing the arguments. If you click on it anyway without any arguments it should just open the file without knowing the exact function definition. When the file is open you can just press Ctrl-Shift-O (outline) and it will show you all functions in the file. You can then enter the function name you want to show the definition of in there.

If you want more features for go to definition, auto completion, documentation or similar things consider creating an issue on Hackerpilot/DCD first and I will make it work with code-d as quickly as possible once it's implemented

**Comment by Damanox** [comment]
filename is not a function, it's a variable, screenshot doesn't show it, here is readConfig definition:
private bool readConfig(string filename, ref Config config)
Made a few tests, it seems that it's working properly for the lines at file start and glitches towards the end of file

**Comment by WebFreak001** [comment]
Hm, does it work if its in the first line? If yes then its probably an issue with the line endings. Does it work if you change them to LF instead of CRLF in the bottom right? DCD isn't always working perfectly either. There is often a problem with auto variables and UFCS but it should work with the normal way of calling. Try making a small source file where you can easily reproduce the issue

**Comment by Damanox** [comment]
> Hm, does it work if its in the first line?
Yes
![1d5c563f36](https://cloud.githubusercontent.com/assets/545324/15722998/24e93ea0-2849-11e6-9bee-96ee563a493b.png)

**Comment by WebFreak001** [comment]
Does it still work with that variable if you copy that same code to the bottom of the file?

**Comment by Damanox** [comment]
Changing line ending doesn't make difference
Forgot to say, but i made some changes to workspace-d code, replaced
line[0 .. $ - 1].split('t');
with
line.chomp().split('t');
because it throws error without this

**Comment by Damanox** [comment]
> Does it still work with that variable if you copy that same code to the bottom of the file?

Nope

**Comment by WebFreak001** [comment]
Is there a delegate somewhere in the middle? DCD gets very unusable for code after delegates

**Comment by Damanox** [comment]
> Is there a delegate somewhere in the middle? DCD gets very unusable for code after delegates

Nope

**Comment by WebFreak001** [comment]
Does it work in the console if you pass it to dcd-client?

**Comment by Damanox** [comment]
Tested in console, works only if file has \r\n line ending
In Code-D does not works regardless of the line ending

**Comment by Damanox** [comment]
Did some research on this bug and found the problem. document.offsetAt returns wrong offset if file contains non-ASCII symbols
If I remove every non-ASCII symbol in my code everything works great

**Comment by WebFreak001** [comment]
Hm now the question: is this DCD's fault for not handling unicode characters as one letter or is it because vscode handles them as multiple letters?

**Comment by Damanox** [comment]
DCD requires byte offset, but vscode works with text, not with it's byte representation, for vscode every symbol length = 1, but non-ASCII symbols consists of 2 bytes, which creates incosistence between dcd and vscode
https://github.com/Microsoft/vscode/issues/5735

**Comment by WebFreak001** [comment]
oh nice I will implement it then when they add it to the API and maybe add a workaround using the nodejs buffer api while they are doing this. Thanks for your research

**Comment by trikko** [comment]
In italian unicode symbols are pretty common, so now I understand why this function never worked for me...
