### ISSUE TITLE
How to disable auto import?

### ISSUE THREAD

**Issue by ryuukk** [Pure-D/code-d#451]
I looked everywhere, i can't find the option to turn this off

Code-d version: v0.23.2

**Comment by WebFreak001** [comment]
This is currently exposed under the `d.enableIndex` property. You won't find it in the latest released code-d version user settings, due to it being a feature newer than that code-d release and the settings UI needing extension updates. (which are bound to the vscode marketplace) However if you open the JSON settings editor you can add `"d.enableIndex": false` there to disable the custom symbol indexing that serve-d does, which is used for auto-complete right now.

However the decision to use this setting was decided upon when this feature was first added and will now also make other features such as find references stop working. I'll add a setting to only disable the auto-completion part, since it's not fully mature yet, however I would appreciate if you could open issues where you don't want the auto-imports to appear, since usually it's quite a useful feature.
