### ISSUE TITLE
Extension killing the CPU

### ISSUE THREAD

**Issue by llaine** [Pure-D/code-d#53]
Hi,

I'm using code-d with visual studio code on Fedora 23 and I notice that when i'm using autocompletion, linting and everything my CPU start screaming and when I looked at the process, I have 4/5 dmd compiling in parallel, all coming from the code-d extension. 

- How can I specify to the extension not to do this? 

Here is a screenshot of the TOP

![capture d ecran de 2016-06-09 11-28-13](https://cloud.githubusercontent.com/assets/3087812/15924977/665b9e90-2e35-11e6-98f8-6242ae0eb99b.png)

**Comment by WebFreak001** [comment]
It's because of the dub linting. It will compile the program without linking or dependency checks and report the errors to the extension. I don't think there is a way to reduce CPU usage in that yet. Try saving less or disable dub linting in your config. If it's only for that project, you can change the workspace settings from the command palette (Ctrl-Shift-P). Otherwise just disable it in your user settings which are also accessible from the command palette.

To disable it simply add this to your json file: `"d.enableDubLinting": false`

**Comment by llaine** [comment]
Okay actually it solves the problem! 
Thank you!
