### ISSUE TITLE
Broken syntax highlighting for variadic arguments.

### ISSUE THREAD

**Issue by Mihail-K** [Pure-D/code-d#96]
The grammar definition used apparently overlooks variadic arguments.
![](http://puu.sh/t145h/5957896afb.png)

This is not made better by a font with ligatures.

**Comment by WebFreak001** [comment]
right now only in the code-d-beta package which will be merged into master eventually, but it's fixed once it's in there. Switched to https://github.com/ysgard/d-struct grammar now because it looks a lot better maintained and the authors suggested me to use it in the atom extension which I will also do
